### ISSUE TITLE
1.5版本启动服务器时发生错误 "java.lang.VerifyError: Operand stack underflow"

### ISSUE THREAD

**Issue by lnelg10** [lanzhi6/BluestarTpsControl#1]
使用1.5版本的插件时启动服务器会出现错误，但1.3版本可以正常运行
系统环境：
JAVA 17
Windows 10
Spigot-1.18.2
8GB内存
仅安装了这一个插件
错误报告如下：

> 

[11:19:08] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:19:08] [ServerMain/INFO]: [STDOUT]: [BluestarTpsControl] Class net.minecraft.server.MinecraftServer 变更成功
[11:19:12] [Worker-Main-20/INFO]: Loaded 7 recipes
[11:19:15] [Server thread/INFO]: Starting minecraft server version 1.18.2
[11:19:15] [Server thread/INFO]: Loading properties
[11:19:16] [Server thread/INFO]: This server is running CraftBukkit version 3481-Spigot-42b6152-e87f2e3 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)
[11:19:16] [Server thread/INFO]: Debug logging is disabled
[11:19:16] [Server thread/INFO]: [BluestarTpsControl] Class org.spigotmc.TicksPerSecondCommand 变更成功
[11:19:16] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.VerifyError: Operand stack underflow
Exception Details:
  Location:
    org/spigotmc/TicksPerSecondCommand.BluestarTpsControlFormat(D)Ljava/lang/String; @1: invokespecial
  Reason:
    Attempt to pop empty stack.
  Current Frame:
    bci: @1
    flags: { }
    locals: { double, double_2nd }
    stack: { double, double_2nd }
  Bytecode:
    0000000: 26b7 005b b0                           

	at org.spigotmc.SpigotConfig.tpsCommand(SpigotConfig.java:280) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3481-Spigot-42b6152-e87f2e3]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.spigotmc.SpigotConfig.readConfig(SpigotConfig.java:110) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3481-Spigot-42b6152-e87f2e3]
	at org.spigotmc.SpigotConfig.init(SpigotConfig.java:76) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3481-Spigot-42b6152-e87f2e3]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:196) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3481-Spigot-42b6152-e87f2e3]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1007) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3481-Spigot-42b6152-e87f2e3]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3481-Spigot-42b6152-e87f2e3]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[11:19:16] [Server thread/WARN]: Failed to get system info for World Generation
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.storage.SaveData.B()" because "this.p" is null
	at net.minecraft.server.MinecraftServer.lambda$20(MinecraftServer.java:1463) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3481-Spigot-42b6152-e87f2e3]
	at net.minecraft.SystemReport.a(SourceFile:65) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3481-Spigot-42b6152-e87f2e3]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1462) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3481-Spigot-42b6152-e87f2e3]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1070) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3481-Spigot-42b6152-e87f2e3]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3481-Spigot-42b6152-e87f2e3]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[11:19:16] [Server thread/ERROR]: This crash report has been saved to: G:\SERVERTPS\.\crash-reports\crash-2022-04-22_11.19.16-server.txt
[11:19:16] [Server thread/INFO]: Stopping server
[11:19:16] [Server thread/INFO]: Saving players
[11:19:17] [Server thread/INFO]: Saving worlds
[11:19:17] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

**Comment by CyanTachyon** [comment]
好的,我会尽快修复,可以先使用1.4/1.3版本,无大差异
